#%RAML 1.0 DataType
type: object
displayName: metaData
properties: 
  success:
    type: boolean
  appName:
    type: string
    required: false
  appVersion:
    type: string
    required: false
  correlationId:
    type: string
    required: false
  timestamp:
    type: string
    required: false